version: "3.4"

services:
  elegant:
    build:
      dockerfile: runtime.dockerfile
      context: .

    command: ["bash"]

    volumes:
      - "./:/elegant"

    ipc: "host"

    # Compose analogue for `--gpus`.
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
